# Домашнее задание «Библиотека numpy. Вычислительные задачи»

## Задание 1
#### Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [96]:
import numpy as np
import random

In [145]:
number = int(input())
res = np.arange(number,-1,-1)
res

8


array([8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2
#### Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [170]:
# Считаем кол-во элементов в матрице

res.shape

(9,)

In [171]:
# Функция для вычисления корня квадратного

np.sqrt(res.shape)

array([3.])

In [172]:
# Построение матрицы

res.reshape(int(np.sqrt(res.shape)), int(np.sqrt(res.shape)))

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [173]:
# Решение задния 2.

number2 = int(input())
res2 = np.arange(number2,-1,-1)
if np.sqrt(res2.shape) % 1 != 0:
    print(input('Введите другое число: '))
else:
    mat = res2.reshape(int(np.sqrt(res2.shape)), int(np.sqrt(res2.shape)))
mat

99


array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0]])

In [174]:
diag = np.asarray(mat)
print ('Diagonal (sum): ', np.trace(diag))
print ('Diagonal (elements): ', np.diagonal(diag))

Diagonal (sum):  495
Diagonal (elements):  [99 88 77 66 55 44 33 22 11  0]


In [175]:
backdiag = np.asarray(mat)
backdiag = np.fliplr(backdiag)
print ('Antidiagonal (sum): ', np.trace(backdiag))
print ('Antidiagonal (elements): ', np.diagonal(backdiag))

Antidiagonal (sum):  495
Antidiagonal (elements):  [90 81 72 63 54 45 36 27 18  9]


## Задание 3
#### Решите систему уравнений:  
4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3

In [182]:
# Коэффициенты при переменных в левой части уравнения

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [183]:
# Значения в правой части уравнения

b = np.array( [4, 12, -3] )

In [184]:
from numpy import linalg

In [185]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [186]:
# Проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

## Задание 4
#### Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [196]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

#### На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [5]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

#### Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [192]:
import matplotlib.pyplot as plt

In [206]:
user_1 = np.array(users_stats[0])
user_2 = np.array(users_stats[1])
user_3 = np.array(users_stats[2])
user_4 = np.array(users_stats[3])
user_5 = np.array(users_stats[4])
user_6 = np.array(users_stats[5])
user_7 = np.array(users_stats[6])
user_8 = np.array(users_stats[7])
user_9 = np.array(users_stats[8])
user_10 = np.array(users_stats[9])

In [208]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [234]:
line = [cosine(user_1, next_user_stats), cosine(user_2, next_user_stats), cosine(user_3, next_user_stats), cosine(user_4, next_user_stats), cosine(user_5, next_user_stats), cosine(user_6, next_user_stats), cosine(user_7, next_user_stats), cosine(user_8, next_user_stats), cosine(user_9, next_user_stats), cosine(user_10, next_user_stats)]
for el in enumerate(line):
    print(el)

(0, 0.19999999999999996)
(1, 0.8451542547285165)
(2, 0.3999999999999999)
(3, 0.7905694150420948)
(4, 0.3999999999999999)
(5, 0.0)
(6, 0.0)
(7, 0.9486832980505138)
(8, 0.0)
(9, 0.0)


In [ ]:
# Посетитель с id = 8 наиболее похож на next_user.